apiVersion: v2
name: graph-db
description: Graph database API service using Neo4j
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: neo4j
  version: 5.29.0
  repository: https://neo4j.github.io/helm-charts
  condition: neo4j.enabled
