{{- if .Values.dticData.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dtic-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: dtic-data
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - {{ .Values.dticData.accessMode }}
  {{- if .Values.dticData.storageClass }}
  storageClassName: {{ .Values.dticData.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.dticData.size }}
{{- end }}
