networks:
  aegisnet:
    driver: bridge

services:
  example-service:
    build: ../services/example-service
    ports:
      - 8001:8001
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aegisnet
