services:
  ldap-server:
    image: symas/openldap:latest
    container_name: ldap-server
    environment:
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_PORT_NUMBER=1389
      - LDAP_MDB_MAPSIZE=2147483648
    volumes:
      # Use these paths for Symas to ensure persistence works
      - ./ldap_data:/var/symas/openldap-data/
      - ./ldap_config:/opt/symas/etc/openldap/slapd.d/
    ports:
      - "1389:1389"
    restart: unless-stopped

  api-gateway:
    build: .
    container_name: api-gateway
    environment:
      - LDAP_SERVER=ldap://ldap-server:1389
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_BASE_DN=dc=example,dc=org
      - AUTH_JSONL_FILE_PATH=/data/dtic_authors_001.jsonl.gz
      - ORG_JSONL_FILE_PATH=/data/dtic_orgs_001.jsonl.gz
    volumes:
      - ../../data/dtic_compressed:/data
    ports:
      - "8000:8000"
    depends_on:
      - ldap-server
    restart: unless-stopped